require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Disable reloading — the app runs in Docker so hot-reload isn't useful
  # and the per-request file-change scan adds measurable latency.
  config.enable_reloading = false

  # Eager load all code at boot (pairs with enable_reloading = false).
  config.eager_load = true

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    # Deployment
    # config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
    # Devlopment
    config.public_file_server.headers = { "cache-control" => "no-store" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  config.log_level = :warn
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  config.active_record.verbose_query_logs = false
  config.active_record.query_log_tags_enabled = false
  config.active_job.verbose_enqueue_logs = false

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  config.action_view.annotate_rendered_view_with_filenames = false

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  config.importmap.cache_sweepers = [Rails.root.join("app/javascript")]

  config.web_console.whitelisted_ips = []

  config.hosts << "aegis.sec"
  config.hosts << "scanaegis.com"
  config.hosts << "www.scanaegis.com"

  # Mailer host — set APP_HOST in .env to control email link domain.
  # APP_PORT is intentionally excluded — scanaegis.com is served on standard ports via reverse proxy.
  # Read directly from ENV (not Aegis.config) since environment files load before initializers.
  config.action_mailer.default_url_options = { host: ENV.fetch("APP_HOST", "localhost") }

  # Resend SMTP — key loaded from .env by dotenv-rails
  config.action_mailer.delivery_method    = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.smtp_settings = {
    address:   "smtp.resend.com",
    port:      465,
    user_name: "resend",
    password:  ENV["RESEND_API_KEY"],
    ssl:       true
  }
end
